### ISSUE TITLE
Unlimited Resources Glitch

### ISSUE THREAD

**Issue by Alanilily** [Hyricon-Development/Faliactyl#3]
![image](https://user-images.githubusercontent.com/83780883/179399345-1eab5d13-018c-4e93-9935-cd89cdd9660d.png)

Some ppl has managed to bug the client into giving them unlimited resources.

**Comment by Alanilily** [comment]
![image](https://user-images.githubusercontent.com/83780883/179399943-2e784412-ce02-4e04-8453-931a2e93434c.png)

And somehow someone already had a huge amount of coins

**Comment by acktarcodes** [comment]
I reported these vulnerabilities in the previous version. Looks like staff didnt bother to fix it :)

**Comment by Alanilily** [comment]
> I reported these vulnerabilities in the previous version. Looks like staff didnt bother to fix it :)

wow i had to switch to a new client cause of it

**Comment by RianOP** [comment]
Did you try setting maximum resources for the egg in settings.yml?

**Comment by Alanilily** [comment]
> Did you try setting maximum resources for the egg in settings.yml?

I have but it didnt really solve anything sure they could not go over hte limit but they still have unlimited resources.

**Comment by Prajwal433** [comment]
> I reported these vulnerabilities in the previous version. Looks like staff didnt bother to fix it :)

Sorry We Had An Issue In Discord So We Couldn't See her

**Comment by Prajwal433** [comment]
> ![image](https://user-images.githubusercontent.com/83780883/179399943-2e784412-ce02-4e04-8453-931a2e93434c.png)
> 
> And somehow someone already had a huge amount of coins

My Relpy Is Its Mentiones An Admin have added there coins it's not possible without it

**Comment by Alanilily** [comment]
> > ![image](https://user-images.githubusercontent.com/83780883/179399943-2e784412-ce02-4e04-8453-931a2e93434c.png)
> > And somehow someone already had a huge amount of coins
> 
> My Relpy Is Its Mentiones An Admin have added there coins it's not possible without it

They had that much coins before my admin just added 2k more coins as a reward

**Comment by Prajwal433** [comment]
> > > ![image](https://user-images.githubusercontent.com/83780883/179399943-2e784412-ce02-4e04-8453-931a2e93434c.png)
> > > And somehow someone already had a huge amount of coins
> > 
> > 
> > My Relpy Is Its Mentiones An Admin have added there coins it's not possible without it
> 
> They had that much coins before my admin just added 2k more coins as a reward

can u send me that user tag?
send the user tag in our support server

**Comment by Prajwal433** [comment]
> ![image](https://user-images.githubusercontent.com/83780883/179399345-1eab5d13-018c-4e93-9935-cd89cdd9660d.png)
> 
> Some ppl has managed to bug the client into giving them unlimited resources.

showing 1 image cant explain everything need to be explained how did it happen

**Comment by Alanilily** [comment]
> > > > ![image](https://user-images.githubusercontent.com/83780883/179399943-2e784412-ce02-4e04-8453-931a2e93434c.png)
> > > > And somehow someone already had a huge amount of coins
> > > 
> > > 
> > > My Relpy Is Its Mentiones An Admin have added there coins it's not possible without it
> > 
> > 
> > They had that much coins before my admin just added 2k more coins as a reward
> 
> can u send me that user tag? send the user tag in our support server

Which user tag?

**Comment by Alanilily** [comment]
> > ![image](https://user-images.githubusercontent.com/83780883/179399345-1eab5d13-018c-4e93-9935-cd89cdd9660d.png)
> > Some ppl has managed to bug the client into giving them unlimited resources.
> 
> showing 1 image cant explain everything need to be explained how did it happen

i mean as i said i have no idea how this happened they jsut randomly got it, after i used it just after some hrs my staff started complaining about ppl managing to get unlimited stuff.

**Comment by acktarcodes** [comment]
> > I reported these vulnerabilities in the previous version. Looks like staff didnt bother to fix it :)
> 
> Sorry We Had An Issue In Discord So We Couldn't See her

but you guys litterally replied to me lmao

**Comment by Prajwal433** [comment]
> commented

Yes I Am Not Allways On Githhub

**Comment by Prajwal433** [comment]
> > > ![image](https://user-images.githubusercontent.com/83780883/179399345-1eab5d13-018c-4e93-9935-cd89cdd9660d.png)
> > > Some ppl has managed to bug the client into giving them unlimited resources.
> > 
> > 
> > showing 1 image cant explain everything need to be explained how did it happen
> 
> i mean as i said i have no idea how this happened they jsut randomly got it, after i used it just after some hrs my staff started complaining about ppl managing to get unlimited stuff.

there is no way of that glitch 
1. some admin is abusing his powers 
2. we dont have any of this bugs

**Comment by manouel-1** [comment]
well ask them how do they do this bug

**Comment by Prajwal433** [comment]
@Alanilily No relpy so far 
relpy in 2 days or it will be closed as (fake bug)

**Comment by RianOP** [comment]
So, after investigating this, there is no evidence of where the bug came from, the only evidence provided is an admin setting the coins of another user. I have come to the conclusion that this isn't a bug or glitch.
