### ISSUE TITLE
bugs I found

### ISSUE THREAD

**Issue by Mrfixit935** [Hyricon-Development/Faliactyl#5]
1. minero 

when enabled (true) i get https://gyazo.com/17de3e6757164dd0aa648976e3b69f19

when its disabled (false) It works

2. status/uptime This is what I got https://gyazo.com/1762f9c63a92abc265bd36f35ac2b631

~3. when you press on discord it redirects you to discord.com/invitecode~
~https://gyazo.com/1563e5fc3e1110cf5a6a6265e1216928~
 ~instead of discord.gg/invitecode~

~4. the widget on the right side. when I open it I get https://gyazo.com/a06dbabed79a1c72f438a2f885abe811~

I can not confirm if theses  bugs are actually their bugs but those are problems that I encountered 

suggestions. 

Make it so you can change the website picture and logo to your own logo and name

**Comment by Prajwal433** [comment]
3. if does work you need to add discord.com/invite/code or discord.gg/code
4. you need to add widget offical bot (not form hyricon) to your server

**Comment by RianOP** [comment]
1. Did you add a key for minero?
2. You didn't setup the status/uptime page correctly.

**Comment by RianOP** [comment]
1. This bug is fixed in v2.1.0
2. You didn't setup the status/uptime page correctly.
